@component('mail::message')
    # Daily Report<br>
    Report Date : {{Carbon\Carbon::yesterday()->toDateString()}}


@component('mail::table')
    | <p class="heading_">Employee Name</p>              | <p class="heading_">CheckIn</p>                                                                                                    |  <p class="heading_">CheckOut</p>                                                                                              |<p class="heading_">Time</p>                                                                                                                                                                                                                                                                                                                                        |        <p class="heading_">Break</p>                                                                                  |     <p class="heading_">Total</p>                                                                                               |<p class="heading_">Hours Logged</p>                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   <p class="heading_">Status  </p>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
        |----------------------------|----------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
        @foreach($report_attendance as $attendance)
            @if($attendance->getOriginal('time_spent') != null)
                | <p class="heading_">{{$attendance->user->name}}</p> |{{ $attendance->time_spent != 'No Time Spent'?date('g:i A',strtotime($attendance->check_in_time)):' '}}|{{$attendance->time_spent != 'No Time Spent'?date('g:i A',strtotime($attendance->check_out_time)):' '}} |@php  if($attendance->check_in_time && $attendance->check_out_time){ $checkin=\Carbon\Carbon::parse($attendance->check_in_time);$checkout=\Carbon\Carbon::parse($attendance->check_out_time); $minutes = $checkin->diffInRealMinutes($checkout); $time=\App\Attendance::mktimecustom(date('H:i', mktime(0,$minutes))); echo $time;}@endphp  |{{$attendance->break_interval?\App\Attendance::mktimecustom($attendance->break_interval):' '}} |{{$attendance->time_spent != 'No Time Spent'?\App\Attendance::mktimecustom($attendance->time_spent):' '}}|@php$get_task=$attendance->task_report; $day=\Carbon\Carbon::today();@endphp  @foreach ($get_task as $get_time)  @php if ($get_time->time_take){$explode_time = explode(':', $get_time->time_take); $total = ($explode_time[0]*60) + ($explode_time[1]); $combined_time=$day->addRealMinutes($total);}  @endphp @endforeach @php  if(isset($combined_time)){ echo (\App\Attendance::mktimecustom($combined_time->toTimeString())); unset($combined_time); }else{ echo (' ');}@endphp      | @if(\App\Helper\Helper::check_informed_late($attendance->getOriginal('attendance_type')) == true ){{' '}}@elseif(\App\Helper\Helper::check_uninformed_late($attendance->getOriginal('attendance_type')) == true ) <p class="heading_">{{substr($attendance->attendance_type,0 ,10)}}</p>@else <p class="heading_">{{$attendance->attendance_type }}</p>@endif @if($attendance->getOriginal('late_informed') == false) @if($attendance->inform(\Carbon\Carbon::parse($attendance->check_in_time)->startOfDay()->timestamp,\Carbon\Carbon::parse($attendance->check_in_time)->endOfDay()->timestamp)) {!!$attendance->getOriginal('attendance_type') != 'check_in'?$attendance->inform(\Carbon\Carbon::parse($attendance->check_in_time)->startOfDay()->timestamp,\Carbon\Carbon::parse($attendance->check_in_time)->endOfDay()->timestamp)->inform_type == "LATE"?"<p class='heading_'>".$attendance->attendance_type."</p>":'':''!!}  @endif @else <p class='heading_'>{{$attendance->late_informed}}</p> @endif|
            @endif
            @if($attendance->getOriginal('time_spent') != null)
             @php
             $leave_checker =true;
             @endphp
            @endif
        @endforeach
@endcomponent

@if($leave_checker == true)

@component('mail::table')

    | <p class="heading_">Employee Name</p>             | <p class="heading_">Type</p>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |              <p class="heading_">Status</p>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
        |---------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
        @foreach($report_attendance as $attendance)
            @if($attendance->getOriginal('time_spent') == null )
                | <p class="heading_">{{$attendance->user->name}}</p>|{{\App\Helper\Helper::check_on_time($attendance->attendance_type) == true ?'':str_replace('leave', '', $attendance->attendance_type)}} <p style="color: darkgoldenrod">{{$attendance->late_informed?$attendance->late_informed:''}}</p>|@if($attendance->leave_comment){{$attendance->inform(\Carbon\Carbon::parse($attendance->check_in_time)->startOfDay()->timestamp,\Carbon\Carbon::parse($attendance->check_in_time)->endOfDay()->timestamp)?$attendance->inform(\Carbon\Carbon::parse($attendance->check_in_time)->startOfDay()->timestamp,\Carbon\Carbon::parse($attendance->check_in_time)->endOfDay()->timestamp)->inform_type == "LEAVE"? $attendance->inform(\Carbon\Carbon::parse($attendance->check_in_time)->startOfDay()->timestamp,\Carbon\Carbon::parse($attendance->check_in_time)->endOfDay()->timestamp)->request_id != null && $attendance->leave_comment != null?$attendance->inform(\Carbon\Carbon::parse($attendance->check_in_time)->startOfDay()->timestamp,\Carbon\Carbon::parse($attendance->check_in_time)->endOfDay()->timestamp)->get_request_leave->approved:'':'':''}} &nbsp;{{$attendance->inform(\Carbon\Carbon::parse($attendance->check_in_time)->startOfDay()->timestamp,\Carbon\Carbon::parse($attendance->check_in_time)->endOfDay()->timestamp)?$attendance->inform(\Carbon\Carbon::parse($attendance->check_in_time)->startOfDay()->timestamp,\Carbon\Carbon::parse($attendance->check_in_time)->endOfDay()->timestamp)->inform_type == "LEAVE"?$attendance->inform(\Carbon\Carbon::parse($attendance->check_in_time)->startOfDay()->timestamp,\Carbon\Carbon::parse($attendance->check_in_time)->endOfDay()->timestamp)->leaves->name  :' ':' '}}@elseif($attendance->leave_comment == null && $attendance->leave_id != null){{$attendance->leave->name}} @else {{'Casual'}}@endif |
            @endif
        @endforeach
@endcomponent

@endif

    Thanks,

    {{ config('app.name') }}
@endcomponent
